# Message sent when no portal was found with the user input.
no-portal-found: 'No portal found with that name!'

# Message sent when selections are needed but none are found.
no-selections: '&red&No WorldEdit selections available!'

# Message sent when a portal has been created.
created-portal: '&green&Successfully created portal with name: [%portal_name%](color=yellow suggest_command=/portal edit %portal_name% show_text=Click to edit!)'

# Message sent when a portal has been updated.
updated-portal: '&green&Successfully updated portal: &yellow&%portal_name%'

# Portals list message! You may add as many messages as you want to the header, but the listing format must ALWAYS be the last message.
portals-list:
  - '[All Portals List](yellow bold)'
  - '&gray&- Portal [%portal_name%](color=blue suggest_command=/portal edit %portal_name% show_text=Click to edit!) &dark_gray&(&aqua&&%max_point% &dark_gray&- &dark_aqua&%min_point%&dark_gray&)'
